hw10_proj/hw10_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes_app.urls")),
    path("login/", include("user_app.urls")),
]

hw10_proj/quotes_app/urls.py
from django.urls import path

from . import views

app_name = "quotes_app"

urlpatterns = [
    path("", views.main, name="root"),
    path("<int:page>", views.main, name="root_paginate"),
    path("author/<str:id_>", views.author, name="author"),
    path("tag/<str:tag_>", views.tags, name="tags"),
    path("author-add/", views.AuthorView.as_view(), name="author-add"),
    path("quote-add/", views.QuoteView.as_view(), name="quote-add"),
    path("tag-add/", views.TagView.as_view(), name="tag-add"),
    path("fillall/", views.fillAll, name="fillall"),
    path("scrap/", views.scrap, name="scrap"),
]

hw10_proj/user_app/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from . import views


app_name = "user_app"

urlpatterns = [
    path("signup/", views.RegisterView.as_view(), name="signup"),
    path("signin/", views.loginuser, name="login"),
    path("logout/", views.logoutuser, name="logout"),
    path("reset-password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(template_name="user_app/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="user_app/password_reset_confirm.html",
            success_url="/login/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(template_name="user_app/password_reset_complete.html"),
        name="password_reset_complete",
    ),
]

hw10_proj/user_app/models.py
from django.db import models

# Create your models here.

hw10_proj/user_app/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import CharField, EmailInput, TextInput, EmailField, PasswordInput


class RegisterForm(UserCreationForm):
    username = CharField(
        max_length=30,
        min_length=3,
        required=True,
        widget=TextInput(attrs={"class": "form-control"}),
    )
    email = EmailField(
        max_length=30,
        required=True,
        widget=EmailInput(
            attrs={"class": "form-control"},
        ),
    )
    password1 = CharField(required=True, widget=PasswordInput(attrs={"class": "form-control"}))
    password2 = CharField(required=True, widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")


class LoginForm(AuthenticationForm):
    username = CharField(
        max_length=50,
        min_length=3,
        required=True,
        widget=TextInput(attrs={"class": "form-control"}),
    )
    password = CharField(required=True, widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ("username", "password")

hw10_proj/user_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views import View
from .forms import RegisterForm, LoginForm
from django.contrib import messages
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin

from django.contrib.auth.views import LogoutView

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from django.template import loader
from django.urls import reverse_lazy


# Create your views here.
class RegisterView(View):
    template_name = "user_app/register.html"
    form_class = RegisterForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to="quotes_app:root")
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_name, context={"form": self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            messages.success(request, f"{username} account was created")
            return redirect(to="user_app:login")
        return render(request, self.template_name, {"form": form})


def loginuser(request):
    if request.user.is_authenticated:
        return redirect(to="quotes_app:root")

    if request.method == "POST":
        user = authenticate(username=request.POST["username"], password=request.POST["password"])
        if user is None:
            messages.error(request, f"Username or password didn't match")
            return redirect(to="user_app:login")

        login(request, user)
        return redirect(to="quotes_app:root")

    return render(request, "user_app/login.html", context={"form": LoginForm()})


@login_required
def logoutuser(request):
    logout(request)
    return render(request, "user_app/logout.html", context={})


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = "user_app/password_reset.html"
    email_template_name = "user_app/password_reset_email.html"
    html_email_template_name = "user_app/password_reset_email.html"
    success_url = reverse_lazy("user_app:password_reset_done")
    success_message = (
        "An email with instructions to reset your password has been sent to %(email)s."
    )
    subject_template_name = "user_app/password_reset_subject.txt"

hw10_proj/user_app/templates/user_app/login.html
{% extends 'quotes_app/base.html' %}


{% block content %}

<div class="container mt-3">
    <h2 class="text-center mb-5">Login Form</h2>

    {% if messages %}
    <div class="message">
        {% for message in messages %}
            <span {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
                {{ message }}
            </span>
        {% endfor %}
    </div>
    {% endif %}

    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{ form.non_field_errors }}
    </div>
    {% endif %}

    <form action="{% url 'user_app:login' %}" method="post">
        {% csrf_token %}
        <div class="form-floating mb-3">
            {{ form.username }}
            <label for="fullname">Username:</label>
            <span>{{ form.errors.username }}</span>
        </div>
    
        <div class="form-floating mb-3">
            {{ form.password }}
            <label for="password">Password:</label>
            <span class="text-danger">{{ form.errors.password1 }}</span>
        </div>
    
        <div class="d-flex flex-column flex-md-row justify-content-between gap-2">
            <button type="submit" class="btn btn-outline-success me-md-2" style="flex: 2;">Submit</button>
            <button type="reset" class="btn btn-secondary" style="flex: 0.5;">Reset</button>
        </div>
        <div class="text-center text-muted mt-3 mb-0">
            <a href="{% url 'user_app:password_reset' %}">
                <i>Forgot Password?</i>
            </a>
        </div>
    </form>
</div>


{% endblock %}

hw10_proj/user_app/templates/user_app/logout.html
{% extends 'quotes_app/base.html' %}


{% block content %}

<div class="container mt-3">
    <h2 class="text-center mb-5">Come back we're waiting for you</h2>
</div>

<div class="text-center text-muted mt-5 mb-0">
    <a href="{% url 'quotes_app:root' %}">
        <u>Return to the home page</u>
    </a>
</div>

{% endblock %}

hw10_proj/user_app/templates/user_app/password_reset.html
{% extends 'quotes_app/base.html' %}

{% block content %}

<h2>Password reset</h2>
<form action="{% url 'user_app:password_reset' %}" method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit" class="btn btn-secondary">
        Request password reset
    </button>
</form>

{% endblock %}

hw10_proj/user_app/templates/user_app/password_reset_complete.html
{% extends 'quotes_app/base.html' %}

{% block content %}

    <h2>Password reset complete!</h2>

{% endblock %}

hw10_proj/user_app/templates/user_app/password_reset_confirm.html
{% extends 'quotes_app/base.html' %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

hw10_proj/user_app/templates/user_app/password_reset_done.html
{% extends 'quotes_app/base.html' %}

{% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

hw10_proj/user_app/templates/user_app/password_reset_email.html
{% autoescape off %}
<body>
    <p>Hi {{ user.username }},</p>
    <p>You requested a password reset for your account. Please follow this link to set a new password:</p>
    <p>
        <a href="{{ protocol }}://{{ domain }}{% url 'user_app:password_reset_confirm' uidb64=uid token=token %}">
            {{ protocol }}://{{ domain }}{% url 'user_app:password_reset_confirm' uidb64=uid token=token %}
        </a>
    </p>
    <p>If you didn't request a password reset, please ignore this email.</p>
    <p>Thanks,</p>
    <p>The Our Team</p>
</body>
{% endautoescape %}

hw10_proj/user_app/templates/user_app/register.html
{% extends 'quotes_app/base.html' %}


{% block content %}

<div class="container mt-3">
    <h2 class="text-center mb-5">Register Form</h2>

    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{ form.non_field_errors }}
    </div>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        <div class="form-floating mb-3">
            {{ form.username }}
            <label for="fullname">Fullname</label>
            <span>{{ form.errors.username }}</span>
        </div>

        <div class="form-floating mb-3">
            {{ form.email }}
            <label for="email">Email address</label>
            <span class="text-danger">{{ form.errors.email }}</span>
        </div>

        <div class="form-floating mb-3">
            {{ form.password1 }}
            <label for="password">Password</label>
            <span class="text-danger">{{ form.errors.password1 }}</span>
        </div>

        <div class="form-floating mb-3">
            {{ form.password2 }}
            <label for="confirm_password">Repeat Password </label>
            <span class="text-danger">{{ form.errors.password2 }}</span>
        </div>

        <div class="d-flex flex-column flex-md-row justify-content-between gap-2">
            <button type="submit" class="btn btn-outline-success me-md-2" style="flex: 2;">Submit</button>
            <button type="reset" class="btn btn-secondary" style="flex: 0.5;">Reset</button>
        </div>

        <div class="text-center text-muted mt-5 mb-0">Do you already have an account?
            <a href="{% url 'user_app:login' %}">
                <u>Login here</u>
            </a>
        </div>
    </form>

</div>


{% endblock %}

hw10_proj/user_app/templates/user_app/userinfo.html
{%if user.is_authenticated %}
<div class="text-end mb-3 text-secondary">
	<span class="text-sm-end">User: {{ user.username }}</span><br>
	<span class="text-sm-end">Email: {{ user.email }}</span>
</div>
{% endif %}