hw10_proj/hw10_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes_app.urls")),
    path("login/", include("user_app.urls")),
]

hw10_proj/quotes_app/urls.py
from django.urls import path

from . import views

app_name = "quotes_app"

urlpatterns = [
    path("", views.main, name="root"),
    path("<int:page>", views.main, name="root_paginate"),
    path("author/<str:id_>", views.author, name="author"),
    path("tag/<str:tag_>", views.tags, name="tags"),
    path("author-add/", views.AuthorView.as_view(), name="author-add"),
    path("quote-add/", views.QuoteView.as_view(), name="quote-add"),
    path("tag-add/", views.TagView.as_view(), name="tag-add"),
    path("fillall/", views.fillAll, name="fillall"),
    path("scrap/", views.scrap, name="scrap"),
]

hw10_proj/user_app/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from . import views


app_name = "user_app"

urlpatterns = [
    path("signup/", views.RegisterView.as_view(), name="signup"),
    path("signin/", views.loginuser, name="login"),
    path("logout/", views.logoutuser, name="logout"),
    path("reset-password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(template_name="user_app/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="user_app/password_reset_confirm.html",
            success_url="/login/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(template_name="user_app/password_reset_complete.html"),
        name="password_reset_complete",
    ),
]

hw10_proj/quotes_app/models.py
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Author(models.Model):
    fullname = models.CharField(max_length=100, null=False, unique=True)
    born_date = models.DateField()
    born_location = models.CharField(max_length=150)
    description = models.TextField(null=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.fullname

    class Meta:
        ordering = ["fullname"]


class Tag(models.Model):
    name = models.CharField(max_length=50, null=False)

    def __str__(self):
        return f"{self.name}"


class Quote(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    tags = models.ManyToManyField(Tag)
    quote = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def get_tags(self):
        return self.tags.split(",")

hw10_proj/quotes_app/forms.py
from django import forms
from django.forms import (
    CharField,
    DateField,
    DateInput,
    ModelChoiceField,
    Select,
    TextInput,
    Textarea,
    ModelMultipleChoiceField,
    SelectMultiple,
)

from .models import Author, Quote, Tag


class AuthorForm(forms.ModelForm):
    fullname = CharField(
        max_length=100,
        min_length=3,
        required=True,
        widget=TextInput(attrs={"class": "form-control", "placeholder": "Fullname"}),
    )
    born_date = DateField(
        required=True,
        widget=DateInput(
            attrs={"class": "form-control", "placeholder": "Born Date"},
        ),
    )
    born_location = CharField(
        max_length=150,
        min_length=3,
        required=True,
        widget=TextInput(
            attrs={"class": "form-control", "placeholder": "Born Location"},
        ),
    )
    description = CharField(
        required=True,
        widget=Textarea(
            attrs={
                "class": "form-control",
                "placeholder": "Description",
                "style": "height: 200px;",
            }
        ),
    )

    class Meta:
        model = Author
        fields = ("fullname", "born_date", "born_location", "description")


class QuoteForm(forms.ModelForm):
    author = ModelChoiceField(
        queryset=Author.objects.all(), required=True, widget=Select(attrs={"class": "form-select"})
    )
    tags = ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=SelectMultiple(
            attrs={
                "class": "form-select",
                "style": "height: 150px;",
            }
        ),
    )
    quote = CharField(
        required=True,
        widget=Textarea(
            attrs={
                "class": "form-control",
                "placeholder": "Quote",
                "style": "height: 100px;",
            }
        ),
    )

    class Meta:
        model = Quote
        fields = ("author", "tags", "quote")


class TagForm(forms.ModelForm):
    name = CharField(
        required=True, widget=Textarea(attrs={"class": "form-control", "placeholder": "Tag"})
    )

    class Meta:
        model = Tag
        fields = ("name",)

hw10_proj/quotes_app/views.py
from unittest import loader
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.views import View
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Count


from .models import Author, Quote, Tag
from .forms import AuthorForm, QuoteForm, TagForm
from .utils import get_mongodb, fill_start

from .scraping.scrap import start_scrap


db = get_mongodb()


# Create your views here.
def main(request, page=1):
    quotes = Quote.objects.all()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)

    top_tags = Tag.objects.annotate(quote_count=Count("quote")).order_by("-quote_count")[:10]
    context = {
        "quotes": quotes_on_page,
        "top_tags": top_tags,
    }

    return render(request, "quotes_app/index.html", context)


def author(request, id_=1):
    author = Author.objects.get(id=id_)
    return render(request, "quotes_app/author.html", context={"author": author})


def tags(request, tag_=""):
    quotes = Quote.objects.filter(tags__name__in=[tag_]).order_by("id").all()
    context = {
        "tag_": tag_,
        "quotes": quotes,
    }
    return render(request, "quotes_app/tags.html", context)


class AuthorView(View):
    template_name = "quotes_app/author_add.html"
    form_class = AuthorForm
    form_class1 = TagForm

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect(to="quotes_app:root")
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(
            request,
            self.template_name,
            context={
                "form": self.form_class,
                "form1": self.form_class1,
            },
        )

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()

        return render(
            request,
            self.template_name,
            {
                "form": form,
                "form1": self.form_class1,
            },
        )


class QuoteView(View):
    template_name = "quotes_app/quote_add.html"
    form_class = QuoteForm

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect(to="quotes_app:root")
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_name, context={"form": self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()

        return render(request, self.template_name, context={"form": form})


class TagView(View):
    template_name = "quotes_app/tag_add.html"
    form_class = TagForm

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect(to="quotes_app:root")
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_name, context={"form": self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()

        return render(request, self.template_name, {"form": form})


@login_required
def fillAll(request):
    fill_start()
    return redirect(to="quotes_app:root")


@login_required
def scrap(request):
    start_scrap()
    return redirect(to="quotes_app:root")


def testing(request):
    template = loader.get_template("user_app/usertest.html")
    return HttpResponse(template.render())

hw10_proj/quotes_app/templates/quotes_app/author.html
{% extends 'quotes_app/base.html' %}


{% block content %}

<div class="author-details">
    <h3 class="author-title">{{author.fullname}}</h3>
    <p>
        <strong>Born:</strong> 
        <span class="author-born-date">
            {{author.born_date}}
        </span> 
        <span class="author-born-location">
            {{author.born_location}}
        </span>
    </p>
    <p>
        <strong>Description:</strong>
    </p>
    <div class="author-description">
        {{author.description}}    
    </div>
</div>

{% endblock %}

hw10_proj/quotes_app/templates/quotes_app/author_add.html
{% extends 'quotes_app/base.html' %}


{% block content %}

<div class="container mt-3">
    <h2 class="text-center mb-5">Author Add</h2>

    {% if messages %}
    <div class="message">
        {% for message in messages %}
            <span {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
                {{ message }}
            </span>
        {% endfor %}
    </div>
    {% endif %}

    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{ form.non_field_errors }}
    </div>
    {% endif %}

    <form action="{% url 'quotes_app:author-add' %}" method="post">
        {% csrf_token %}
        <div class="form-floating mb-3">
            {{ form.fullname }}
            <label for="fullname">Author Fullname:</label>
            <span>{{ form.errors.fullname }}</span>
        </div>
    
        <div class="form-floating mb-3">
            {{ form.born_date }}
            <label for="born_date">Born Date (YYYY-MM-DD):</label>
            <span class="text-danger">{{ form.errors.born_date }}</span>
        </div>

        <div class="form-floating mb-3">
            {{ form.born_location }}
            <label for="born_location">Born Location:</label>
            <span class="text-danger">{{ form.errors.born_location }}</span>
        </div>
       
        <div class="form-floating mb-3">
            {{ form.description }}
            <label for="description">Description:</label>
            <span class="text-danger">{{ form.errors.description }}</span>
        </div>
    
        <div class="d-flex flex-column flex-md-row justify-content-between gap-2">
            <button type="submit" class="btn btn-outline-success me-md-2" style="flex: 2;">Submit</button>
            <button type="reset" class="btn btn-secondary" style="flex: 0.5;">Reset</button>
        </div>
        
    </form>
    
    
</div>

<div>
    <div class="container mt-3">
        <h2 class="text-center mb-5">Tag Add</h2>
        
        {% if messages %}
        <div class="message">
            {% for message in messages %}
            <span {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
                {{ message }}
            </span>
            {% endfor %}
        </div>
        {% endif %}
        
        {% if form1.errors and form.non_field_errors %}
        <div class="alert alert-danger" role="alert">
            {{ form1.non_field_errors }}
        </div>
        {% endif %}
        
        <form action="{% url 'quotes_app:tag-add' %}" method="post">
            {% csrf_token %}
            <div class="form-floating mb-3">
                {{ form1.name }}
                <label for="name">Name:</label>
                <span>{{ form1.errors.name }}</span>
            </div>
            
            <div class="d-flex flex-column flex-md-row justify-content-between gap-2">
                <button type="submit" class="btn btn-outline-success me-md-2" style="flex: 2;">Submit</button>
                <button type="reset" class="btn btn-secondary" style="flex: 0.5;">Reset</button>
            </div>
        </form>
        <div class="text-center text-muted mt-5 mb-0">Do you want to add quotes for the author?
            <a href="{% url 'quotes_app:quote-add' %}">
                <u>Quote Add</u>
            </a>
        </div>
    </div>
</div>


{% endblock %}

hw10_proj/quotes_app/templates/quotes_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" 
        rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" 
        crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes_app/style.css' %}">
    <title>Quotes to Scrape HW10</title>
</head>
<body>
    <div class="container">
        <div class="row header-box">
            <div class="col-md-5">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-7">
                <p>
                    <a href="{% url 'quotes_app:root' %}" class="link-login">Home</a>
                    {%if user.is_authenticated %}
                    <a href="{% url 'quotes_app:author-add' %}" class="link-login">Author Add</a>
                    <a href="{% url 'quotes_app:quote-add' %}" class="link-login">Quote Add</a>
                    <a href="{% url 'user_app:logout' %}" class="link-login">Logout</a>
                    <a href="{% url 'quotes_app:scrap' %}" class="link-login">Scrap</a>
                    <a href="{% url 'quotes_app:fillall' %}" class="link-login">MongoDB to Postgres</a>
                    {% else %}
                    <a href="{% url 'user_app:login' %}" class="link-login">Login</a>
                    <a href="{% url 'user_app:signup' %}" class="link-login">Register</a>
                    {% endif %}
                </p>
            </div>
            {% include "user_app/userinfo.html" %}
        </div>
        {% block content %} 
        {% endblock %}
    </div>
</body>
</html>

hw10_proj/quotes_app/templates/quotes_app/index.html
{% extends 'quotes_app/base.html' %}

{% comment %} {% extends 'user_app/userinfo.html' %} {% endcomment %}

{% comment %} {% load extract %} {% endcomment %}

{% block userinfo %}

{% endblock %}


{% block content %}

<div class="row">
    <!-- <p>Количество цитат: {{ quotes|length }}</p> -->
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote">
            <span class="text" itemprop="text">
                {{quote.quote}}
            </span>
            <span>by <small class="author" itemprop="author">
                {{quote.author}}
            </small>
            <a href="{% url 'quotes_app:author' quote.author.id %}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                <a class="tag" href="{% url 'quotes_app:tags' tag %}">{{tag}}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}

        <nav>
            <ul class="pager">  
                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                       href="{% if quotes.has_previous %} {% url 'quotes_app:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                        <span aria-hidden="true">←</span> Previous
                    </a>
                </li>
                <li class="next">
                    <a class="{% if not quotes.has_next %} disabled {% endif %}"
                       href="{% if quotes.has_next %}{% url 'quotes_app:root_paginate' quotes.next_page_number %}{% else %}#{% endif %}"> 
                        Next <span aria-hidden="true">→</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
    <div class="col-md-4 tags-box">
        <h2 class="text-center mb-3">Top Ten tags</h2>
        {% for tag in top_tags %}
            <div class="text-end mb-3">
                <a class="tag"
                    style="font-size: {% if forloop.counter0 == 0 %} 28px {% endif %}
                                      {% if forloop.counter0 == 1 %} 26px {% endif %}
                                      {% if forloop.counter0 == 2 %} 26px {% endif %}
                                      {% if forloop.counter0 == 3 %} 24px {% endif %}
                                      {% if forloop.counter0 == 4 %} 22px {% endif %}
                                      {% if forloop.counter0 == 5 %} 14px {% endif %}
                                      {% if forloop.counter0 == 6 %} 10px {% endif %}
                                      {% if forloop.counter0 == 7 %} 8px {% endif %}
                                      {% if forloop.counter0 == 8 %} 8px {% endif %}
                                      {% if forloop.counter0 == 9 %} 6px {% endif %}"
                    href="{% url 'quotes_app:tags' tag %}">{{ tag }}
                </a>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

hw10_proj/quotes_app/templates/quotes_app/quote_add.html
{% extends 'quotes_app/base.html' %}


{% block content %}

<div class="container mt-3">
    <h2 class="text-center mb-5">Quote Add</h2>

    {% if messages %}
    <div class="message">
        {% for message in messages %}
            <span {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
                {{ message }}
            </span>
        {% endfor %}
    </div>
    {% endif %}

    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{ form.non_field_errors }}
    </div>
    {% endif %}

    <form action="{% url 'quotes_app:quote-add' %}" method="post">
        {% csrf_token %}
        <div class="form-floating mb-3">
            {{ form.author }}
            <label for="author">Author Fullname:</label>
            <span>{{ form.errors.author }}</span>
        </div>
    
        <div class="form-floating mb-3"> 
            {{ form.tags }}
            <label for="{{ form.tags.id_for_label }}">Select Tags:</label>
            <span class="text-danger">{{ form.errors.tags }}</span>
        </div>

        <div class="form-floating mb-3">
            {{ form.quote }}
            <label for="quote">Quote:</label>
            <span class="text-danger">{{ form.errors.quote }}</span>
        </div>
    
        <div class="d-flex flex-column flex-md-row justify-content-between gap-2">
            <button type="submit" class="btn btn-outline-success me-md-2" style="flex: 2;">Submit</button>
            <button type="reset" class="btn btn-secondary" style="flex: 0.5;">Reset</button>
        </div>
    </form>
</div>


{% endblock %}

hw10_proj/quotes_app/templates/quotes_app/tag_add.html
{% extends 'quotes_app/base.html' %}


{% block content %}

<div class="container mt-3">
    <h2 class="text-center mb-5">Tag Add</h2>

    {% if messages %}
    <div class="message">
        {% for message in messages %}
            <span {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
                {{ message }}
            </span>
        {% endfor %}
    </div>
    {% endif %}

    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{ form.non_field_errors }}
    </div>
    {% endif %}

    <form action="{% url 'quotes_app:tag-add' %}" method="post">
        {% csrf_token %}
        <div class="form-floating mb-3">
            {{ form.name }}
            <label for="name">Name:</label>
            <span>{{ form.errors.name }}</span>
        </div>
    
        <div class="d-flex flex-column flex-md-row justify-content-between gap-2">
            <button type="submit" class="btn btn-outline-success me-md-2" style="flex: 2;">Submit</button>
            <button type="reset" class="btn btn-secondary" style="flex: 0.5;">Reset</button>
        </div>
    </form>
</div>


{% endblock %}

hw10_proj/quotes_app/templates/quotes_app/tags.html
{% extends 'quotes_app/base.html' %}
{% load extract %}

{% block content %}
<h3>
    Viewing tag: 
    <a href="#">{{tag_}}</a>
</h3>

<div class="col-md-8">
    {% for quote in quotes %}
    <div class="quote">
        <span class="text" itemprop="text">
            {{quote.quote}}
        </span>
        <span>by <small class="author" itemprop="author">
            {{quote.author}}
        </small>
        <a href="{% url 'quotes_app:author' quote.author.id %}">(about)</a>
        </span>
        <div class="tags">
            Tags:
            {% for tag in quote.tags.all %}
            <a class="tag" href="{% url 'quotes_app:tags' tag %}">{{tag}}</a>
            {% endfor %}
        </div>
    </div>
    {% endfor %}
    
{% endblock%}